### ISSUE TITLE
搬砖有风险 谨慎防砸脚

### ISSUE THREAD

**Issue by qs-lll** [liaohuqiu/btcbot-open#1]
@liaohuqiu 可以出一个 追涨杀跌机器人 风险相对低些

**Comment by liaohuqiu** [comment]
@qs-lll 嗯，这个在计划中，不过相比这个，我更希望加入的 `高买低卖` 的特性，相信一定能满足广大炒币同学的喜好。

**Comment by xiyangyang8110** [comment]
是高抛低吸吧
